name: Npm Upstream Check
description: Check the updates of upstream npm dependencies
author: ArcherGu
branding:
  icon: refresh-cw
  color: blue

inputs:
  upstream:
    description: upstream npm dependencies
    required: true
  deep:
    description: deep check
    required: false
  check-only:
    description: 'only check, not update package.json'
    required: false
  all:
    description: update all npm dependencies in package.json
    required: false

outputs:
  need-update:
    description: need update
  dependencies:
    description: dependencies need update with version

runs:
  using: node20
  main: dist/index.js
