catalog:
  '@actions/core': ^3.0.0
  '@actions/github': ^9.0.0
  '@lightwing/eslint-config': ^1.0.151
  '@types/node': ^25.5.0
  eslint: ^10.1.0
  lint-staged: ^16.4.0
  npm-check-updates: ^21.0.0
  simple-git-hooks: ^2.13.1
  tsdown: ^0.21.7
  typescript: ^6.0.2
  vitest: ^4.1.2
  yaml: ^2.8.3

catalogMode: prefer
cleanupUnusedCatalogs: true
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks

shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
  - '@octokit/plugin-paginate-rest@9.2.2'
  - undici@5.29.0
  - '@octokit/endpoint@9.0.6'
