catalog:
  '@actions/core': ^3.0.1
  '@actions/github': ^9.1.1
  '@lightwing/eslint-config': ^1.0.156
  '@types/node': ^26.1.1
  '@typescript/native': npm:typescript@7.0.2
  eslint: ^10.7.0
  lint-staged: ^17.0.8
  npm-check-updates: ^22.2.9
  simple-git-hooks: ^2.13.1
  tsdown: ^0.22.8
  typescript: npm:@typescript/typescript6@6.0.2
  vitest: ^4.1.10
  yaml: ^2.9.0

catalogMode: prefer
cleanupUnusedCatalogs: true
allowBuilds:
  esbuild: true
  simple-git-hooks: true

shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
  - '@octokit/plugin-paginate-rest@9.2.2'
  - undici@5.29.0
  - '@octokit/endpoint@9.0.6'
minimumReleaseAgeExclude:
  - npm-check-updates@22.2.1 || 22.2.3
  - '@eslint/plugin-kit@0.7.2'
  - eslint@10.4.1
  - '@types/node@25.9.3'
  - '@vitest/expect@4.1.9'
  - '@vitest/mocker@4.1.9'
  - '@vitest/pretty-format@4.1.9'
  - '@vitest/runner@4.1.9'
  - '@vitest/snapshot@4.1.9'
  - '@vitest/spy@4.1.9'
  - '@vitest/utils@4.1.9'
  - vitest@4.1.9
  - rolldown-plugin-dts@0.27.8
  - tsdown@0.22.7 || 0.22.8
